module.exports = {
    formHead:{
       fontSize:30,
       color:'white',
       textAlign:'center',
       fontWeight:'bold'
    },
    formInput:{
        width:'80%',
        backgroundColor:'white',
        borderRadius:10,
        marginVertical:10,
        paddingHorizontal:15,
        paddingVertical:10,
        fontSize:18
    },
    formbtn:{
        width:'80%',
        backgroundColor:'black',
        borderRadius:10,
        borderColor:'white',
        borderWidth:1,
        color:'white',
        textAlign:'center',
        marginVertical:10,
        paddingVertical:10,
        fontSize:25
    },
    formTextLinkRight:{
        color:'grey',
        fontSize:15,
        textAlign:'right',
        width:'80%',
        marginVertical:10,
    },
    formTextLinkCenter:{
        color:'grey',
        fontSize:16,
    },
    formHead2:{
        fontSize:20,
        color:'white',
        textAlign:'center',
        
    },
    formHead3:{
        fontSize:20,
        color:'grey',
        textAlign:'center',
        formWeight:'400',
        padding:10,
        borderRadius:10,
        width:'80%',
        marginVertical:10,
    }
}